skillstack/config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories
  resources :bookings
  resources :lessons
  resources :users
  resources :home, only: [:index]

  resources :lessons do 
    member do
      put "like", to: "lessons#upvote"
      put "dislike", to: "lessons#downvote"
    end
  end

  root 'static_pages#home'
  get "/login", to: "sessions#new"
  delete "/logout", to: "sessions#destroy"
  get "/mylessonbookings", to: "lessons#teacher_lessons"
end

skillstack/app/models/booking.rb
class Booking < ActiveRecord::Base
  validates :time, presence: true
  validates :date, presence: true

  belongs_to :lesson
  belongs_to :student, class_name: 'User', foreign_key: 'student_id'
end

skillstack/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :lessons
end

skillstack/app/models/lesson.rb
class Lesson < ActiveRecord::Base
  mount_uploader :image_one, AvatarUploader
  mount_uploader :image_two, AvatarUploader
  mount_uploader :image_three, AvatarUploader
  
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :description, presence: true
  validates :description, length: { maximum: 350 }
  validates :location, presence: true
  validates :cost, presence: true

  geocoded_by :location
  after_validation :geocode

  belongs_to :teacher, class_name: 'User', foreign_key: 'teacher_id'
  has_many :bookings, dependent: :destroy
  belongs_to :category
  acts_as_votable
end

skillstack/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :bio, presence: true
  
  mount_uploader :avatar, AvatarUploader

  has_many :lessons, class_name: 'Lesson', foreign_key: 'teacher_id', dependent: :destroy
  has_many :bookings, class_name: 'Booking', foreign_key: 'student_id', dependent: :destroy

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
end

skillstack/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    @current_user ||=User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !! current_user
  end

  def authenticate
    unless logged_in?
      flash[:error] = "You must be logged in to access this page"
      redirect_to login_url
    end
  end

  def authenticate_user(user)
    if user != current_user
      flash[:error] = "You are not authorized to do that. Please login."
      redirect_to root_path
    else 
      true
    end
  end

end

skillstack/app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def index
    @bookings = current_user.bookings
  end

  def show
  end

  def new
    @booking = Booking.new
  end

  def edit
  end

  def create
   params[:booking][:student_id] = current_user.id
   @booking = Booking.new(booking_params)
   if @booking.save
     redirect_to @booking
   else
     render :new
   end
 end

 def update
  respond_to do |format|
    if @booking.update(booking_params)
      format.html { redirect_to @booking }
    else
      format.html { render :edit }
    end
  end
end

def destroy
  @booking.destroy
  respond_to do |format|
    format.html { redirect_to bookings_url }
  end
end

private
def set_booking
  @booking = Booking.find(params[:id])
end

def booking_params
  params.require(:booking).permit(:lesson_id, :student_id, :time, :date)
end
end

skillstack/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
    end
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :description)
  end
end

skillstack/app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  def index
    @search = Lesson.search(params[:q])
    @lessons = @search.result
    @categories = Category.all
  end

  def teacher_lessons
    @lessons = current_user.lessons
    render :teacher_lessons
  end

  def upvote 
    @lesson = Lesson.find(params[:id])
    @lesson.upvote_by current_user
    redirect_to :back
  end  

  def downvote
    @lesson = Lesson.find(params[:id])
    @lesson.downvote_by current_user
    redirect_to :back
  end

  def show
    @categories = Category.all
  end

  def new
    @lesson = Lesson.new
  end

  def edit
  end

  def create
   params[:lesson][:teacher_id] = current_user.id
   @lesson = Lesson.new(lesson_params)
   if @lesson.save
     redirect_to @lesson
   else
     render :new
   end
 end

 def update
  respond_to do |format|
    if @lesson.update(lesson_params)
      format.html { redirect_to @lesson }
    else
      format.html { render :edit }
    end
  end
end

def destroy
  @lesson.destroy
  respond_to do |format|
    format.html { redirect_to lessons_url }
  end
end

private
def set_lesson
  @lesson = Lesson.find(params[:id])
end

def lesson_params
  params.require(:lesson).permit(:title, :description, :image_one, :image_two, :image_three, :location, :cost, :teacher_id, :category_id, :city, :longitute, :latitude)
end
end

skillstack/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user
    else 
      flash.now.alert = "Invalid Login Credentials"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

skillstack/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @search = Lesson.search(params[:q])
    @lessons = @search.result
    @categories = Category.all
  end
end

skillstack/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
    redirect_to @user unless authenticate_user(@user)
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :bio, :image, :password, :password_confirmation, :email, :avatar)
  end
end

skillstack/app/helpers/application_helper.rb
module ApplicationHelper
end

skillstack/app/helpers/session_helper.rb
module SessionHelper
end

skillstack/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

skillstack/app/views/application/_header.html.erb
<header>
  <nav>
    <ul>
      <li><%= link_to "skillstack", root_url %></li>
      <% if current_user %>
      <li><%= link_to "Logout", logout_path, method: :delete, data: { confirm: "Are you sure?" } %></li>
      <li><a href="/users/<%= current_user.id %>">View Profile</a></li>
      <li><%= link_to "Create Lesson", new_lesson_path, class: "create_lesson" %></li>
      <% else %>
      <li><%= link_to "Login", login_path %></li>
      <% end %>
      <li><%= link_to "View Lessons", lessons_path %></li>
    </ul>
  </nav>
</header>

skillstack/app/views/bookings/_booking.html.erb
<div class="user_show_own_bookings">
  <div class="all_bookings">
    <p><span class="bold">Date:</span> <%= booking.date %></p>
    <p><span class="bold">Time:</span> <%= booking.time %></p>
    <p class="delete"><%= link_to 'Delete', booking, method: :delete, data: { confirm: 'Are you sure?' } %></p>
  </div>
  <%= render booking.lesson %>
</div>

skillstack/app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
<% if @booking.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

  <ul>
    <% @booking.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<h2><%= @booking.lesson.try(:title) %></h2>

<div class="field">
  <%= f.label :time %><br>
  <%= f.text_field :time %>
</div>
<div class="field">
  <%= f.label :date %><br>
  <%= f.text_field :date %>
</div>
<%= f.hidden_field :lesson_id, value: params["lesson_id"] %>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

skillstack/app/views/bookings/index.html.erb
<main>
  <div class="user_details">
    <p><%= link_to 'Edit Profile', edit_user_path(current_user) %></p>
    <p><%= link_to 'View Bookings', bookings_path %></p>
    <p><%= link_to "View Lessons", "/mylessonbookings" %></p>
  </div>
  <h1>My Bookings</h1>
  <% if current_user.bookings.count == 0 %>
  <p>You have made 0 bookings! <%= link_to 'Click here', lessons_path, class: "bold" %> to browse available lessons.</p>
  <% end %>
  <div class="bookings_index_container">
    <%= render @bookings %>
  </div>
</main>

skillstack/app/views/bookings/new.html.erb
<main>
  <h1>New Booking</h1>
  <%= render 'form' %>
</main>

skillstack/app/views/bookings/show.html.erb
<main>
  <div class="booking_confirmation">
    <h2>Your booking has been requested!</h2>
    <p><span class="bold">Time:</span> <%= @booking.time %></p>
    <p><span class="bold">Date:</span> <%= @booking.date %></p>
  </div>
  <%= render @booking.lesson %>
</main>

skillstack/app/views/categories/_category.html.erb
<%= link_to category.name, category %>
  

skillstack/app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

skillstack/app/views/categories/edit.html.erb
<main>
  <h1>Editing Category</h1>
  <%= render 'form' %>
  <%= link_to 'Show', @category %> |
  <%= link_to 'Back', categories_path %>
</main>

skillstack/app/views/categories/index.html.erb
<main>
  <h1>Categories</h1>
  <%= render @categories %>
  <%= link_to 'New Category', new_category_path %>
</main>

skillstack/app/views/categories/new.html.erb
<main>
  <h1>New Category</h1>
  <%= render 'form' %>
  <%= link_to 'Back', categories_path %>
</main>

skillstack/app/views/categories/show.html.erb
<main>
  <h2><%= @category.name %> Lessons</h2>
  <div class="category_container">
    <% @categories.each do |category| %>
    <%= link_to category.name, category, class: "category_button" %><br>
    <% end %>
  </div>
  <div class="category_lessons_container">
    <%= render @category.lessons %>
  </div>
</main>

skillstack/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>skillstack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Quicksand:400,300,700' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="wrapper">
    <%= render "header" %>
    <% flash.each do |name, message| %>
    <div class="flash-message flash-message-<%= name %>">
      <%= message %>
    </div>
    <% end %>
    <%= yield %>
    <div class="push"></div>
  </div>
  <div class ="footer">
    <p>skillstack &copy;</p>
  </div>
</body>
</html>

skillstack/app/views/lessons/_form.html.erb
<%= form_for(@lesson) do |f| %>
<% if @lesson.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

  <ul>
    <% @lesson.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</div>
<div class="field">
  <%= f.label :description %><br>
  <p class="small">Max. 350 characters</p>
  <%= f.text_area :description %>
</div>
<div class="field">
  <%= f.label :image %><br>
  <%= f.file_field :image_one %>
</div>
<div class="field">
  <%= f.label :location %><br>
  <p class="small">E.g. Soho, London</p>
  <%= f.text_field :location %>
</div>
<div class="field">
  <%= f.label :cost %><br>
  <%= f.text_field :cost %>
</div>
<div class="field">
  <%= f.label :category_id %><br>
  <%= f.collection_select(:category_id, Category.all, :id, :name) %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

skillstack/app/views/lessons/_lesson.html.erb
<div class="lesson_index">
  <ul>
    <div class="lesson_index_image">
      <%= link_to lesson do %>
      <%= image_tag lesson.image_one.lesson_index %>
      <% end %>
    </div>
    <li><h3><%= link_to lesson.title, lesson %> <%= link_to lesson.category.try(:name), lesson.category, class: "small_category_button" %></h3></li>
    <li><p class="lesson_teacher">with <%= link_to lesson.teacher.try(:first_name) + " " + lesson.teacher.try(:last_name), lesson.teacher %></p></li>
    <li><p><%= truncate(lesson.description, :length => 120) %></p></li>
    <li><p class="lesson_small_details"><%= lesson.location %></p></li>
    <li><p class="lesson_small_details"><%= number_to_currency lesson.cost, :unit => "£" %></p></li>
    <li><%= link_to like_lesson_path(lesson), method: :put do %>
      <span class="small_likes_button">Likes: <%= lesson.get_upvotes.size %></span>
      <% end %></li>
    </ul>
  </div>

skillstack/app/views/lessons/edit.html.erb
<main>
  <h1>Editing Lesson</h1>
  <%= render 'form' %>
  <p class="delete"><%= link_to 'Delete', @lesson, method: :delete, data: { confirm: 'Are you sure?' } %></p>
</main>

skillstack/app/views/lessons/index.html.erb
<main>
  <h2>All Lessons</h2>
  <div class="lesson_index_main_container">
    <div class="lesson_index_container">
      <%= render @lessons %>
    </div>
    <div class ="category_container">
      <% @categories.each do |category| %>
      <%= link_to category.name, category, class: "category_button" %>
      <% end %> 
    </div>
  </div>
</main>

skillstack/app/views/lessons/new.html.erb
<main>
  <h1>Create Lesson</h1>
  <%= render 'form' %>
</main>

skillstack/app/views/lessons/show.html.erb
<main>
  <div class="lesson_show_info">
    <div class="lesson_show_main_image">
      <% if current_user == @lesson.teacher %>
      <%= link_to 'Edit Lesson', edit_lesson_path(@lesson), class: "lesson_edit_button" %>
      <% end %>
      <%= image_tag @lesson.image_one.lesson_main %>
    </div>
    <div class="lesson_show_text">
      <h2><%= @lesson.title %> <%= link_to @lesson.category.try(:name), @lesson.category, class: "small_category_button" %></h2>
      <p class="lesson_teacher">with <%= link_to @lesson.teacher.try(:first_name) + " " + @lesson.teacher.try(:last_name), @lesson.teacher %></p>
      <p><%= @lesson.description %></p>
      <p class="lesson_small_details"><%= @lesson.location %></p>
      <p class="lesson_small_details"><%= number_to_currency @lesson.cost, :unit => "£" %></p>
      <%= link_to like_lesson_path(@lesson), method: :put do %>
      <span class="small_likes_button">Likes: <%= @lesson.get_upvotes.size %></span>
      <% end %>
      <p><%= link_to "Request Booking", "/bookings/new?lesson_id=#{@lesson.id}", class: "request_lesson" %></p>
    </div>
  </div>

  <div class="nearby_main_container">
    <div class ="nearby_lessons">
      <h4>Nearby Lessons</h4>
      <%= render @lesson.nearbys %>
    </div>
    <div class ="category_container">
      <% @categories.each do |category| %>
      <%= link_to category.name, category, class: "category_button" %>
      <% end %> 
    </div>
  </div>
</main>

skillstack/app/views/lessons/teacher_lessons.html.erb
<main>
  <div class="user_details">
    <p><%= link_to 'Edit Profile', edit_user_path(current_user) %></p>
    <p><%= link_to 'View Bookings', bookings_path %></p>
    <p><%= link_to "View Lessons", "/mylessonbookings" %></p>
  </div>

  <h1>Upcoming Lessons</h1>
  <div class="all_teachers_lessons">
    <% @lessons.each do |lesson| %>
    <div class="teachers_lessons">
      <%= link_to lesson do %>
      <%= image_tag lesson.image_one.lesson_index, class: "lesson_booking_image" %>
      <% end %>
      <h3><%= link_to lesson.title, lesson %></h3>
      <% if lesson.bookings.count == 0 %>
      <p>You have 0 bookings for this lesson!</p>
      <% end %>
      <% lesson.bookings.each do |booking| %>
      <div class="individual_lesson_booking">
        <p><span class="bold">Student:</span> <%= link_to booking.student.try(:first_name) + " " + booking.student.try(:last_name), booking.student %></p>
        <p><span class="bold">Date:</span> <%= booking.date %></p>
        <p><span class="bold">Time:</span> <%= booking.time %></p>
      </div>
      <% end %>
    </div>
    <% end %>
  </main>
</div>

skillstack/app/views/static_pages/home.html.erb
<section class="module parallax parallax-1">
  <div class="homepage_banner container">
    <%= search_form_for @search do |f| %>
    <div class="field homepage_search">
      <div class="homepage_search_container">
        <%= f.text_field :title_or_description_cont, :placeholder => "What would you like to learn?" %>
        <%= f.submit "Search" %>
      </div>
    </div>
    <% end %>
  </div>
</section>

<main>
  <h2 class="popular">Popular Lessons</h2>
  <div class="lesson_index_container">
    <%= render @lessons %>
  </div>
  <div class ="category_container">
    <% @categories.each do |category| %>
    <%= link_to category.name, category, class: "category_button" %>
    <% end %> 
  </div>
</main>

skillstack/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %>
</div>
<div class="field">
  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %>
</div>
<div class="field">
  <%= f.label :email %><br>
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :bio %><br>
  <%= f.text_area :bio %>
</div>
<div class="field">
  <%= f.label :avatar %><br>
  <%= f.file_field :avatar %>
</div>
<div class="field">
  <%= f.label :password %><br>
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %>
</div>
<div class="actions"><%= f.submit %></div>
<% end %>

skillstack/app/views/users/_user.html.erb
<li>
  <ul>
    <li><%= user.first_name %></li>
    <li><%= user.last_name %></li>
    <li><%= user.bio %></li>
    <li><%= link_to image_tag(user.avatar.thumb), user %></li>
    <li><%= link_to 'Show', user %></li>
    <li><%= link_to 'Edit', edit_user_path(user) %></li>
    <li><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></li>
  </ul>
</li>

skillstack/app/views/users/edit.html.erb
<main>
  <h1>Edit Profile</h1>
  <%= render 'form' %>
</main>

skillstack/app/views/users/index.html.erb
<main>
  <h1>Listing Users</h1>
  <ul>
    <%= render @users %>
  </ul>
  <%= link_to 'New User', new_user_path %>
</main>

skillstack/app/views/users/new.html.erb
<main>
  <h1>New User</h1>
  <%= render 'form' %>
</main>

skillstack/app/views/users/show.html.erb
<main>
  <div class="user_profile_info">
    <div class="user_avatar">
      <%= image_tag @user.avatar.detail %>
    </div>
    <div class="user_name_bio">
    <h2><%= @user.first_name %> <%= @user.last_name %></h2>
    <p><%= @user.bio %></p>
    </div>
  </div>
  <div class="user_details">
    <p><% if current_user == @user %></p>
    <p><%= link_to 'Edit Profile', edit_user_path(@user) %></p>
    <p><%= link_to 'View Bookings', bookings_path %></p>
    <p><%= link_to "View Lessons", "/mylessonbookings" %></p>
    <% end %>
  </div>
  <div class ="user_show_lessons">
    <h4>Lessons that <%= @user.first_name %> teaches</h4>
    <%= render @user.lessons %>
  </div>
</main>